// shuaituzhibincg/heroui-web/src/pages/ApiTest.tsx
import { useState } from 'react'
import axios from 'axios'
import qs from 'qs'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Send, Copy, Trash2, Monitor } from 'lucide-react'

export default function ApiTest() {
  const [method, setMethod] = useState('GET')
  const [endpoint, setEndpoint] = useState('')
  const [requestBody, setRequestBody] = useState('')
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState<any>(null)
  const [requestTime, setRequestTime] = useState(0)
  const [history, setHistory] = useState<any[]>([])
  const [currentPreset, setCurrentPreset] = useState<string | null>(null)

  const methodOptions = ['GET', 'POST', 'PUT', 'DELETE']

  const presetApis = [
    { label: '获取用户信息', method: 'GET', endpoint: '/v1/user/info' },
    { label: '获取数据库列表', method: 'GET', endpoint: '/v1/databases' },
    { label: '获取同盟成员', method: 'GET', endpoint: '/v1/getTeamUser' },
    { label: '获取任务列表', method: 'GET', endpoint: '/v1/getTaskList' },
    { label: '获取分组', method: 'GET', endpoint: '/v1/getTeamGroup' },
    { label: '获取分组武勋', method: 'GET', endpoint: '/v1/getGroupWu' },
    { label: '登录', method: 'POST', endpoint: '/v1/auth/login', body: 'username=&password=' },
    { label: '注册', method: 'POST', endpoint: '/v1/auth/register', body: 'username=&password=&nickname=' },
    { label: '修改密码', method: 'POST', endpoint: '/v1/user/changePassword', body: 'old_password=&new_password=' },
    { label: '创建数据库', method: 'POST', endpoint: '/v1/databases/create', body: 'name=&display_name=' },
    { label: '认领数据库', method: 'POST', endpoint: '/v1/databases/1/claim' },
    { label: '获取用户列表(管理员)', method: 'GET', endpoint: '/v1/admin/users' }
  ]

  const selectPreset = (preset: any) => {
    setMethod(preset.method)
    setEndpoint(preset.endpoint)
    setRequestBody(preset.body || '')
    setCurrentPreset(preset.label)
  }

  const sendRequest = async () => {
    if (!endpoint) {
      alert('请输入API端点')
      return
    }

    setLoading(true)
    const startTime = Date.now()

    try {
      const config: any = {
        method: method.toLowerCase(),
        url: endpoint,
        withCredentials: true,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }
      }

      if (method !== 'GET' && requestBody) {
        config.data = qs.stringify(Object.fromEntries(new URLSearchParams(requestBody)))
      }

      const res = await axios(config)

      setResponse({
        status: res.status,
        statusText: res.statusText,
        headers: res.headers,
        data: res.data
      })

      setHistory(prev => {
        const newHistory = [{
          method,
          endpoint,
          time: new Date().toLocaleString(),
          status: res.status
        }, ...prev]
        return newHistory.slice(0, 20)
      })
    } catch (error: any) {
      setResponse({
        status: error.response?.status || 0,
        statusText: error.response?.statusText || 'Error',
        headers: error.response?.headers || {},
        data: error.response?.data || { error: error.message }
      })
    } finally {
      setRequestTime(Date.now() - startTime)
      setLoading(false)
    }
  }

  const copyResponse = () => {
    if (response) {
      navigator.clipboard.writeText(JSON.stringify(response.data, null, 2))
      alert('已复制到剪贴板')
    }
  }

  const clearAll = () => {
    setEndpoint('')
    setRequestBody('')
    setResponse(null)
    setCurrentPreset(null)
  }

  const formattedResponse = () => {
    if (!response?.data) return ''
    try {
      return JSON.stringify(response.data, null, 2)
    } catch {
      return String(response.data)
    }
  }

  const statusColor = (status: number) => {
    if (status >= 200 && status < 300) return 'bg-emerald-100 text-emerald-700 hover:bg-emerald-100'
    if (status >= 400 && status < 500) return 'bg-amber-100 text-amber-700 hover:bg-amber-100'
    if (status >= 500) return 'bg-red-100 text-red-700 hover:bg-red-100'
    return 'bg-gray-100 text-gray-700 hover:bg-gray-100'
  }

  return (
    <div className="max-w-7xl mx-auto flex flex-col md:flex-row gap-6 h-[calc(100vh-120px)]">
      <div className="w-full md:w-72 flex-shrink-0 flex flex-col gap-4 h-full overflow-y-auto pr-2">
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-3 border-b border-gray-100 bg-gray-50">
            <h3 className="font-semibold text-gray-700 text-sm">预设 API</h3>
          </div>
          <div className="p-2 space-y-1">
            {presetApis.map(preset => (
              <div
                key={preset.label}
                onClick={() => selectPreset(preset)}
                className={`flex items-center gap-2 p-2 rounded-lg cursor-pointer text-sm transition-colors ${
                  currentPreset === preset.label
                    ? 'bg-blue-50 border border-blue-200 text-blue-700'
                    : 'hover:bg-gray-100 text-gray-700 border border-transparent'
                }`}
              >
                <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${
                  preset.method === 'GET' ? 'bg-gray-200 text-gray-700' : 'bg-emerald-100 text-emerald-700'
                }`}>
                  {preset.method}
                </span>
                <span className="truncate">{preset.label}</span>
              </div>
            ))}
          </div>
        </div>

        {history.length > 0 && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div className="p-3 border-b border-gray-100 bg-gray-50">
              <h3 className="font-semibold text-gray-700 text-sm">请求历史</h3>
            </div>
            <div className="p-2 space-y-1">
              {history.map((item, index) => (
                <div key={`${item.method}-${item.endpoint}-${index}`} className="flex items-center gap-2 p-2 rounded-lg bg-gray-50 border border-gray-100 text-sm">
                  <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${
                    item.method === 'GET' ? 'bg-gray-200 text-gray-700' : 'bg-emerald-100 text-emerald-700'
                  }`}>
                    {item.method}
                  </span>
                  <span className="truncate flex-1 text-gray-600" title={item.endpoint}>{item.endpoint}</span>
                  <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded ${
                    item.status < 300 ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'
                  }`}>
                    {item.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="flex-1 flex flex-col gap-4 h-full overflow-y-auto">
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-3 border-b border-gray-100 bg-gray-50">
            <h3 className="font-semibold text-gray-700 text-sm">请求配置</h3>
          </div>
          <div className="p-4 space-y-4">
            <div className="flex flex-col sm:flex-row gap-2">
              <Select value={method} onValueChange={setMethod}>
                <SelectTrigger className="w-full sm:w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {methodOptions.map(m => (
                    <SelectItem key={m} value={m}>{m}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Input
                className="flex-1"
                placeholder="输入API端点，如: /v1/user/info"
                value={endpoint}
                onChange={e => setEndpoint(e.target.value)}
                onKeyDown={(e: any) => e.key === 'Enter' && sendRequest()}
              />
              <Button className="bg-blue-600 text-white hover:bg-blue-700" onClick={sendRequest} disabled={loading}>
                {!loading && <Send size={16}/>}
                {loading ? '发送中...' : '发送'}
              </Button>
            </div>

            {method !== 'GET' && (
              <div>
                <div className="text-sm font-medium text-gray-600 mb-2">请求体 (application/x-www-form-urlencoded)</div>
                <Textarea
                  value={requestBody}
                  onChange={e => setRequestBody(e.target.value)}
                  placeholder="输入请求参数，如: username=admin&password=123456"
                  rows={4}
                />
              </div>
            )}

            <div>
              <Button variant="outline" onClick={clearAll}>
                <Trash2 size={16}/>清空
              </Button>
            </div>
          </div>
        </div>

        {response ? (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden flex-1 flex flex-col min-h-[300px]">
            <div className="p-3 border-b border-gray-100 bg-gray-50 flex justify-between items-center">
              <h3 className="font-semibold text-gray-700 text-sm">响应结果</h3>
              <div className="flex items-center gap-2">
                <Badge className={statusColor(response.status)}>
                  {response.status} {response.statusText}
                </Badge>
                <Badge variant="secondary">{requestTime}ms</Badge>
                <Button size="sm" variant="ghost" onClick={copyResponse}>
                  <Copy size={14}/>复制
                </Button>
              </div>
            </div>
            <div className="p-4 flex-1 overflow-hidden flex flex-col">
              <div className="text-sm font-medium text-gray-600 mb-2">响应数据</div>
              <pre className="bg-slate-900 text-slate-200 p-4 rounded-lg overflow-auto text-sm font-mono flex-1">
                {formattedResponse()}
              </pre>
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 flex-1 flex items-center justify-center min-h-[300px]">
            <div className="text-center text-gray-400 space-y-3">
              <Monitor size={48} className="mx-auto opacity-50" />
              <p>选择预设API或输入端点后发送请求</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// shuaituzhibincg/web/src/pages/ApiTest.vue
<script setup>
import { ref, computed } from 'vue';
import { ElMessage } from 'element-plus';
import { Promotion, CopyDocument, Delete } from '@element-plus/icons-vue';
import axios from 'axios';
import qs from 'qs';

// API配置
const method = ref('GET');
const endpoint = ref('');
const requestBody = ref('');
const headers = ref([{ key: 'Content-Type', value: 'application/x-www-form-urlencoded' }]);
const response = ref(null);
const loading = ref(false);
const requestTime = ref(0);
const history = ref([]);

// 方法选项
const methodOptions = [
    { label: 'GET', value: 'GET' },
    { label: 'POST', value: 'POST' },
    { label: 'PUT', value: 'PUT' },
    { label: 'DELETE', value: 'DELETE' }
];

// 预设API
const presetApis = [
    { label: '获取用户信息', method: 'GET', endpoint: '/v1/user/info' },
    { label: '获取数据库列表', method: 'GET', endpoint: '/v1/databases' },
    { label: '获取同盟成员', method: 'GET', endpoint: '/v1/getTeamUser' },
    { label: '获取任务列表', method: 'GET', endpoint: '/v1/getTaskList' },
    { label: '获取分组', method: 'GET', endpoint: '/v1/getTeamGroup' },
    { label: '获取分组武勋', method: 'GET', endpoint: '/v1/getGroupWu' },
    { label: '登录', method: 'POST', endpoint: '/v1/auth/login', body: 'username=&password=' },
    { label: '注册', method: 'POST', endpoint: '/v1/auth/register', body: 'username=&password=&nickname=' },
    { label: '修改密码', method: 'POST', endpoint: '/v1/user/changePassword', body: 'old_password=&new_password=' },
    { label: '创建数据库', method: 'POST', endpoint: '/v1/databases/create', body: 'name=&display_name=' },
    { label: '认领数据库', method: 'POST', endpoint: '/v1/databases/1/claim' },
    { label: '获取用户列表(管理员)', method: 'GET', endpoint: '/v1/admin/users' }
];

const currentPreset = ref(null);

// 选择预设API
const selectPreset = (preset) => {
    method.value = preset.method;
    endpoint.value = preset.endpoint;
    if (preset.body) {
        requestBody.value = preset.body;
    } else {
        requestBody.value = '';
    }
    currentPreset.value = preset.label;
};

// 发送请求
const sendRequest = async () => {
    if (!endpoint.value) {
        ElMessage.warning('请输入API端点');
        return;
    }

    loading.value = true;
    const startTime = Date.now();
    
    try {
        let config = {
            method: method.value.toLowerCase(),
            url: endpoint.value,
            withCredentials: true
        };

        // 添加请求头
        const headerObj = {};
        headers.value.forEach(h => {
            if (h.key && h.value) {
                headerObj[h.key] = h.value;
            }
        });
        config.headers = headerObj;

        // 添加请求体
        if (method.value !== 'GET' && requestBody.value) {
            if (headerObj['Content-Type'] === 'application/x-www-form-urlencoded') {
                config.data = qs.stringify(Object.fromEntries(new URLSearchParams(requestBody.value)));
            } else if (headerObj['Content-Type'] === 'application/json') {
                config.data = JSON.parse(requestBody.value);
            } else {
                config.data = requestBody.value;
            }
        }

        const res = await axios(config);
        
        response.value = {
            status: res.status,
            statusText: res.statusText,
            headers: res.headers,
            data: res.data
        };
        
        // 添加到历史
        history.value.unshift({
            method: method.value,
            endpoint: endpoint.value,
            time: new Date().toLocaleString(),
            status: res.status
        });
        if (history.value.length > 20) {
            history.value.pop();
        }
        
    } catch (error) {
        response.value = {
            status: error.response?.status || 0,
            statusText: error.response?.statusText || 'Error',
            headers: error.response?.headers || {},
            data: error.response?.data || { error: error.message }
        };
    } finally {
        requestTime.value = Date.now() - startTime;
        loading.value = false;
    }
};

// 复制响应
const copyResponse = () => {
    if (response.value) {
        navigator.clipboard.writeText(JSON.stringify(response.value.data, null, 2));
        ElMessage.success('已复制到剪贴板');
    }
};

// 清空
const clearAll = () => {
    endpoint.value = '';
    requestBody.value = '';
    response.value = null;
    currentPreset.value = null;
};

// 格式化JSON
const formattedResponse = computed(() => {
    if (!response.value?.data) return '';
    try {
        return JSON.stringify(response.value.data, null, 2);
    } catch {
        return String(response.value.data);
    }
});

// 状态颜色
const statusType = computed(() => {
    if (!response.value) return 'info';
    const status = response.value.status;
    if (status >= 200 && status < 300) return 'success';
    if (status >= 400 && status < 500) return 'warning';
    if (status >= 500) return 'danger';
    return 'info';
});

// 添加请求头
const addHeader = () => {
    headers.value.push({ key: '', value: '' });
};

// 删除请求头
const removeHeader = (index) => {
    headers.value.splice(index, 1);
};
</script>

<template>
    <div class="api-test-page">
        <el-container>
            <!-- 左侧：预设和历史 -->
            <el-aside width="280px" class="left-panel">
                <el-card class="panel-card">
                    <template #header>
                        <span>预设API</span>
                    </template>
                    <div class="preset-list">
                        <div 
                            v-for="preset in presetApis" 
                            :key="preset.label"
                            class="preset-item"
                            :class="{ 'active': currentPreset === preset.label }"
                            @click="selectPreset(preset)"
                        >
                            <el-tag :type="preset.method === 'GET' ? 'info' : 'success'" size="small">
                                {{ preset.method }}
                            </el-tag>
                            <span class="preset-label">{{ preset.label }}</span>
                        </div>
                    </div>
                </el-card>
                
                <el-card class="panel-card" v-if="history.length">
                    <template #header>
                        <span>请求历史</span>
                    </template>
                    <div class="history-list">
                        <div 
                            v-for="(item, index) in history" 
                            :key="index"
                            class="history-item"
                        >
                            <el-tag :type="item.method === 'GET' ? 'info' : 'success'" size="small">
                                {{ item.method }}
                            </el-tag>
                            <span class="history-endpoint">{{ item.endpoint }}</span>
                            <el-tag :type="item.status < 300 ? 'success' : 'danger'" size="small">
                                {{ item.status }}
                            </el-tag>
                        </div>
                    </div>
                </el-card>
            </el-aside>
            
            <!-- 右侧：请求和响应 -->
            <el-main class="right-panel">
                <!-- 请求配置 -->
                <el-card class="panel-card">
                    <template #header>
                        <span>请求配置</span>
                    </template>
                    <div class="request-config">
                        <!-- URL输入 -->
                        <div class="url-input">
                            <el-select v-model="method" style="width: 100px;">
                                <el-option v-for="item in methodOptions" :key="item.value" :label="item.label" :value="item.value" />
                            </el-select>
                            <el-input 
                                v-model="endpoint"
                                placeholder="输入API端点，如: /v1/user/info"
                                clearable
                                @keyup.enter="sendRequest"
                                style="flex: 1;"
                            />
                            <el-button type="primary" :loading="loading" @click="sendRequest">
                                <el-icon><Promotion /></el-icon>
                                发送
                            </el-button>
                        </div>
                        
                        <!-- 请求体 -->
                        <div v-if="method !== 'GET'" class="request-body">
                            <div class="section-label">请求体</div>
                            <el-input 
                                v-model="requestBody"
                                type="textarea"
                                placeholder="输入请求参数，如: username=admin&password=123456"
                                :rows="4"
                            />
                        </div>
                        
                        <!-- 操作按钮 -->
                        <div class="actions">
                            <el-button @click="clearAll">
                                <el-icon><Trash2 /></el-icon>
                                清空
                            </el-button>
                        </div>
                    </div>
                </el-card>
                
                <!-- 响应结果 -->
                <el-card class="panel-card" v-if="response">
                    <template #header>
                        <div class="response-header">
                            <span>响应结果</span>
                            <div class="response-info">
                                <el-tag :type="statusType">
                                    {{ response.status }} {{ response.statusText }}
                                </el-tag>
                                <el-tag type="info">
                                    {{ requestTime }}ms
                                </el-tag>
                                <el-button size="small" @click="copyResponse">
                                    <el-icon><CopyDocument /></el-icon>
                                    复制
                                </el-button>
                            </div>
                        </div>
                    </template>
                    
                    <el-collapse>
                        <el-collapse-item title="响应数据" name="body">
                            <pre class="response-body">{{ formattedResponse }}</pre>
                        </el-collapse-item>
                        <el-collapse-item title="响应头" name="headers">
                            <el-descriptions :column="1" border size="small">
                                <el-descriptions-item v-for="(value, key) in response.headers" :key="key" :label="key">
                                    {{ value }}
                                </el-descriptions-item>
                            </el-descriptions>
                        </el-collapse-item>
                    </el-collapse>
                </el-card>
                
                <!-- 空状态 -->
                <el-card v-else class="panel-card empty-state">
                    <div class="empty-content">
                        <el-icon :size="48" color="#d9d9d9"><Monitor /></el-icon>
                        <p>选择预设API或输入端点后发送请求</p>
                    </div>
                </el-card>
            </el-main>
        </el-container>
    </div>
</template>

<style scoped>
.api-test-page {
    height: calc(100vh - 96px);
}

.left-panel {
    height: 100%;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 16px;
    padding: 0 8px;
    background: #fafafa;
}

.right-panel {
    height: 100%;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 16px;
    padding: 0 20px;
}

.panel-card {
    flex-shrink: 0;
}

.panel-card span {
    font-weight: 500;
}

.preset-list, .history-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.preset-item, .history-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 12px;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s ease;
    background: #fff;
}

.preset-item:hover, .history-item:hover {
    background: #f0f0f0;
}

.preset-item.active {
    background: #fff7e6;
    border: 1px solid #ffd591;
}

.preset-label, .history-endpoint {
    flex: 1;
    font-size: 13px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.request-config {
    display: flex;
    flex-direction: column;
    gap: 16px;
}

.url-input {
    display: flex;
    gap: 8px;
}

.section-label {
    font-size: 13px;
    font-weight: 500;
    color: #666;
    margin-bottom: 8px;
}

.actions {
    display: flex;
    gap: 8px;
}

.response-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
}

.response-info {
    display: flex;
    align-items: center;
    gap: 8px;
}

.response-body {
    background: #f5f7fa;
    padding: 12px;
    border-radius: 4px;
    font-size: 12px;
    overflow-x: auto;
    max-height: 400px;
    overflow-y: auto;
}

.empty-state {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
}

.empty-content {
    text-align: center;
    color: #999;
}

.empty-content p {
    margin-top: 16px;
    font-size: 14px;
}

@media (max-width: 768px) {
    .api-test-page :deep(.el-container) {
        flex-direction: column;
    }
    
    .left-panel {
        width: 100% !important;
        max-height: 300px;
    }
    
    .url-input {
        flex-wrap: wrap;
    }
    
    .url-input .el-select {
        width: 100% !important;
    }
}
</style>
