// shuaituzhibincg/heroui-web/src/pages/GroupWu.tsx
import { useState, useEffect } from 'react'
import { ApiGetGroupWu } from '../api'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { RefreshCcw } from 'lucide-react'

export default function GroupWu() {
  const [loading, setLoading] = useState(false)
  const [groupData, setGroupData] = useState<any[]>([])

  const loadData = async () => {
    setLoading(true)
    try {
      const res = await ApiGetGroupWu()
      if (res.data.code === 200) {
        const data = res.data.data
        if (Array.isArray(data)) {
          const validData = data.map((item: any, idx: number) => ({
            ...item,
            id: item.id || item.group || `group-${idx}`
          }))
          setGroupData(validData)
        } else {
          console.error('分组武勋数据格式错误，期望数组:', data)
          setGroupData([])
        }
      } else {
        console.error('API返回错误:', res.data)
        if (res.data.message === '请先选择数据库') {
          alert('请先在首页选择数据库')
        }
        setGroupData([])
      }
    } catch (error: any) {
      console.error('获取分组武勋数据异常:', error)
      if (error?.response?.data?.message === '请先选择数据库') {
        alert('请先在首页选择数据库')
      }
      setGroupData([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadData()
  }, [])

  return (
    <div className="max-w-4xl mx-auto space-y-4 pb-12">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex items-center gap-3">
          <h2 className="text-xl font-bold text-gray-800">分组武勋</h2>
          <span className="px-3 py-1 text-xs font-semibold text-amber-700 bg-amber-50 rounded-full border border-amber-200">
            更新武勋数据请同步成员数据
          </span>
        </div>
        <Button variant="outline" size="sm" onClick={loadData}>
          <RefreshCcw size={14} className="mr-1" />
          刷新
        </Button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-gray-50">
              <TableHead>分组名称</TableHead>
              <TableHead className="text-center">人数</TableHead>
              <TableHead className="text-right">总武勋</TableHead>
              <TableHead className="text-right">平均武勋</TableHead>
              <TableHead className="text-center">0武勋人数</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center py-8 text-gray-500">加载中...</TableCell>
              </TableRow>
            ) : groupData.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="text-center py-8 text-gray-500">暂无数据</TableCell>
              </TableRow>
            ) : (
              groupData.map((item: any) => (
                <TableRow key={item.id}>
                  <TableCell>
                    <span className="inline-block px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-xs font-medium">
                      {item.group}
                    </span>
                  </TableCell>
                  <TableCell className="text-center">
                    <span className="text-gray-800 font-medium">{item.member_count}</span>
                  </TableCell>
                  <TableCell className="text-right">
                    <span className="text-blue-600 font-bold">{item.total_wu}</span>
                  </TableCell>
                  <TableCell className="text-right">
                    <span className="text-gray-800 font-semibold">{item.average_wu}</span>
                  </TableCell>
                  <TableCell className="text-center">
                    {item.zero_wu_count > 0 ? (
                      <Badge variant="destructive">{item.zero_wu_count}</Badge>
                    ) : (
                      <span className="text-gray-400">0</span>
                    )}
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}

// shuaituzhibincg/web/src/pages/GroupWu.vue
<script setup>
import { ref, onMounted } from "vue";
import { ElMessage } from 'element-plus'
import { Refresh } from '@element-plus/icons-vue'
import { ApiGetGroupWu } from '@/api'

const groupdata = ref([]);

function getData() {
    groupdata.value = [];
    ApiGetGroupWu().then(v => {
        if (v.status == 200) {
            let resp = v.data;
            if (resp.code == 200) {
                let data = resp.data;
                groupdata.value = data;
            } else {
                ElMessage.error(resp.msg);
            }
        } else {
            ElMessage.error("获取分组武勋数据失败");
        }
    });
}

onMounted(() => {
    getData();
});
</script>

<template>
    <div class="group-wu-page">
        <div class="page-header">
            <div class="page-title-area">
                <h2 class="page-title">分组武勋</h2>
                <span class="hint-badge">更新武勋数据请同步成员数据</span>
            </div>
            <el-button @click="getData" :icon="Refresh">刷新</el-button>
        </div>

        <div class="table-card">
            <el-table :data="groupdata" style="width: 100%" :header-cell-style="{ background: 'var(--bg-page)', color: 'var(--text-secondary)', fontWeight: 600 }">
                <el-table-column prop="group" label="分组名称" min-width="120">
                    <template #default="{ row }">
                        <span class="group-tag">{{ row.group }}</span>
                    </template>
                </el-table-column>
                <el-table-column prop="member_count" label="人数" width="90" align="center" />
                <el-table-column prop="total_wu" label="总武勋" width="130" align="right">
                    <template #default="{ row }">
                        <span class="wu-value">{{ row.total_wu }}</span>
                    </template>
                </el-table-column>
                <el-table-column prop="average_wu" label="平均武勋" width="130" align="right">
                    <template #default="{ row }">
                        <span class="avg-value">{{ row.average_wu }}</span>
                    </template>
                </el-table-column>
                <el-table-column prop="zero_wu_count" label="0武勋人数" width="120" align="center">
                    <template #default="{ row }">
                        <span v-if="row.zero_wu_count > 0" class="zero-badge">{{ row.zero_wu_count }}</span>
                        <span v-else class="zero-ok">0</span>
                    </template>
                </el-table-column>
            </el-table>
        </div>
    </div>
</template>

<style scoped>
.group-wu-page {
    max-width: 900px;
    margin: 0 auto;
}

.page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    flex-wrap: wrap;
    gap: 12px;
}

.page-title-area {
    display: flex;
    align-items: center;
    gap: 10px;
}

.page-title {
    margin: 0;
    font-size: 20px;
    font-weight: 700;
    color: var(--text-primary);
}

.hint-badge {
    background: var(--color-warning-light);
    color: #d97706;
    font-size: 12px;
    font-weight: 500;
    padding: 3px 10px;
    border-radius: 20px;
}

.table-card {
    background: var(--bg-card);
    border: 1px solid var(--border-color);
    border-radius: var(--radius-lg);
    padding: 4px;
    box-shadow: var(--shadow-sm);
    overflow: hidden;
}

.group-tag {
    display: inline-block;
    background: var(--bg-hover);
    color: var(--text-secondary);
    font-size: 12px;
    padding: 2px 10px;
    border-radius: 20px;
    font-weight: 500;
}

.wu-value {
    color: var(--color-primary);
    font-weight: 700;
}

.avg-value {
    color: var(--text-primary);
    font-weight: 600;
}

.zero-badge {
    display: inline-block;
    background: var(--color-danger-light);
    color: var(--color-danger);
    font-size: 12px;
    font-weight: 600;
    padding: 2px 10px;
    border-radius: 20px;
}

.zero-ok {
    color: var(--text-tertiary);
}

@media (max-width: 768px) {
    .page-header {
        flex-direction: column;
        align-items: flex-start;
    }
}
</style>
