// shuaituzhibincg/web/src/pages/Password.vue
<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { Lock, ArrowLeft } from '@element-plus/icons-vue';
import { ApiChangePassword } from '../api';

const router = useRouter();

const loading = ref(false);

const form = ref({
    old_password: '',
    new_password: '',
    confirm_password: ''
});

const handleSubmit = async () => {
    if (!form.value.old_password) {
        ElMessage.error('请输入旧密码');
        return;
    }
    if (!form.value.new_password) {
        ElMessage.error('请输入新密码');
        return;
    }
    if (form.value.new_password.length < 6) {
        ElMessage.error('新密码长度至少6个字符');
        return;
    }
    if (form.value.new_password !== form.value.confirm_password) {
        ElMessage.error('两次输入的新密码不一致');
        return;
    }

    loading.value = true;
    try {
        const res = await ApiChangePassword({
            old_password: form.value.old_password,
            new_password: form.value.new_password
        });
        if (res.data.code === 200) {
            ElMessage.success('密码修改成功');
            form.value = {
                old_password: '',
                new_password: '',
                confirm_password: ''
            };
        } else {
            ElMessage.error(res.data.msg);
        }
    } catch (error) {
        ElMessage.error('修改失败：' + (error.message || '网络错误'));
    } finally {
        loading.value = false;
    }
};
</script>

<template>
    <div class="password-page">
        <div class="password-card">
            <div class="card-header">
                <div class="header-icon">
                    <el-icon :size="24"><Lock /></el-icon>
                </div>
                <h2 class="card-title">修改密码</h2>
                <p class="card-desc">请输入当前密码并设置新密码</p>
            </div>

            <el-form label-position="top" class="password-form">
                <el-form-item label="旧密码" required>
                    <el-input
                        v-model="form.old_password"
                        type="password"
                        placeholder="请输入当前密码"
                        show-password
                        prefix-icon="Lock"
                    />
                </el-form-item>
                <el-form-item label="新密码" required>
                    <el-input
                        v-model="form.new_password"
                        type="password"
                        placeholder="请输入新密码（至少6字符）"
                        show-password
                        prefix-icon="Lock"
                    />
                </el-form-item>
                <el-form-item label="确认密码" required>
                    <el-input
                        v-model="form.confirm_password"
                        type="password"
                        placeholder="请再次输入新密码"
                        show-password
                        prefix-icon="Lock"
                        @keyup.enter="handleSubmit"
                    />
                </el-form-item>
                <el-form-item>
                    <div class="form-actions">
                        <el-button @click="router.back()" :icon="ArrowLeft">返回</el-button>
                        <el-button type="primary" :loading="loading" @click="handleSubmit">确认修改</el-button>
                    </div>
                </el-form-item>
            </el-form>
        </div>
    </div>
</template>

<style scoped>
.password-page {
    max-width: 480px;
    margin: 40px auto 0;
}

.password-card {
    background: var(--bg-card);
    border-radius: var(--radius-lg);
    border: 1px solid var(--border-color);
    box-shadow: var(--shadow-sm);
    padding: 32px;
}

.card-header {
    text-align: center;
    margin-bottom: 28px;
}

.header-icon {
    width: 48px;
    height: 48px;
    border-radius: 50%;
    background: var(--color-primary-lighter);
    color: var(--color-primary);
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto 16px;
}

.card-title {
    margin: 0 0 6px;
    font-size: 20px;
    font-weight: 600;
    color: var(--text-primary);
}

.card-desc {
    margin: 0;
    font-size: 13px;
    color: var(--text-tertiary);
}

.password-form :deep(.el-form-item__label) {
    font-weight: 500;
    color: var(--text-secondary);
}

.form-actions {
    display: flex;
    gap: 12px;
    width: 100%;
    padding-top: 8px;
}

.form-actions .el-button {
    flex: 1;
}
</style>

// shuaituzhibincg/heroui-web/src/pages/Password.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiChangePassword } from '../api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { Lock, ArrowLeft } from 'lucide-react'

export default function Password() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    old_password: '',
    new_password: '',
    confirm_password: ''
  })
  const [errorMsg, setErrorMsg] = useState('')

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()

    if (!form.old_password) return setErrorMsg('请输入旧密码')
    if (!form.new_password) return setErrorMsg('请输入新密码')
    if (form.new_password.length < 6) return setErrorMsg('新密码长度至少6个字符')
    if (form.new_password !== form.confirm_password) return setErrorMsg('两次输入的新密码不一致')

    setErrorMsg('')
    setLoading(true)
    try {
      const res = await ApiChangePassword({
        old_password: form.old_password,
        new_password: form.new_password
      })
      if (res.data.code === 200) {
        alert('密码修改成功')
        setForm({ old_password: '', new_password: '', confirm_password: '' })
      } else {
        setErrorMsg(res.data.message || '修改失败')
      }
    } catch (error: any) {
      if (error.response) {
        const data = error.response.data
        setErrorMsg(data?.message || `服务器错误 (${error.response.status})`)
      } else {
        setErrorMsg('修改失败：' + (error.message || '未知错误'))
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-md mx-auto mt-10">
      <Card className="shadow-sm border border-gray-200">
        <CardContent className="p-8">
          <div className="text-center mb-8">
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <Lock size={24} />
            </div>
            <h2 className="text-xl font-bold text-gray-800">修改密码</h2>
            <p className="text-sm text-gray-500 mt-1">请输入当前密码并设置新密码</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label className="mb-1 block">旧密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请输入当前密码"
                  className="pl-9"
                  value={form.old_password}
                  onChange={v => setForm({ ...form, old_password: v.target.value })}
                />
              </div>
            </div>
            <div>
              <Label className="mb-1 block">新密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请输入新密码（至少6字符）"
                  className="pl-9"
                  value={form.new_password}
                  onChange={v => setForm({ ...form, new_password: v.target.value })}
                />
              </div>
            </div>
            <div>
              <Label className="mb-1 block">确认密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请再次输入新密码"
                  className="pl-9"
                  value={form.confirm_password}
                  onChange={v => setForm({ ...form, confirm_password: v.target.value })}
                />
              </div>
            </div>

            {errorMsg && <div className="text-red-500 text-sm">{errorMsg}</div>}

            <div className="flex gap-3 pt-4">
              <Button
                variant="outline"
                className="flex-1"
                type="button"
                onClick={() => navigate(-1)}
              >
                <ArrowLeft size={16} />
                返回
              </Button>
              <Button
                type="submit"
                className="flex-1"
                disabled={loading}
              >
                {loading ? '提交中...' : '确认修改'}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
