// shuaituzhibincg/heroui-web/src/pages/Password.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ApiChangePassword } from '../api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { Lock, ArrowLeft } from 'lucide-react'

export default function Password() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    old_password: '',
    new_password: '',
    confirm_password: ''
  })
  const [errorMsg, setErrorMsg] = useState('')

  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()

    if (!form.old_password) return setErrorMsg('请输入旧密码')
    if (!form.new_password) return setErrorMsg('请输入新密码')
    if (form.new_password.length < 6) return setErrorMsg('新密码长度至少6个字符')
    if (form.new_password !== form.confirm_password) return setErrorMsg('两次输入的新密码不一致')

    setErrorMsg('')
    setLoading(true)
    try {
      const res = await ApiChangePassword({
        old_password: form.old_password,
        new_password: form.new_password
      })
      if (res.data.code === 200) {
        alert('密码修改成功')
        setForm({ old_password: '', new_password: '', confirm_password: '' })
      } else {
        setErrorMsg(res.data.message || '修改失败')
      }
    } catch (error: any) {
      if (error.response) {
        const data = error.response.data
        setErrorMsg(data?.message || `服务器错误 (${error.response.status})`)
      } else {
        setErrorMsg('修改失败：' + (error.message || '未知错误'))
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-md mx-auto mt-10">
      <Card className="shadow-sm border border-gray-200">
        <CardContent className="p-8">
          <div className="text-center mb-8">
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
              <Lock size={24} />
            </div>
            <h2 className="text-xl font-bold text-gray-800">修改密码</h2>
            <p className="text-sm text-gray-500 mt-1">请输入当前密码并设置新密码</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label className="mb-1 block">旧密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请输入当前密码"
                  className="pl-9"
                  value={form.old_password}
                  onChange={v => setForm({ ...form, old_password: v.target.value })}
                />
              </div>
            </div>
            <div>
              <Label className="mb-1 block">新密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请输入新密码（至少6字符）"
                  className="pl-9"
                  value={form.new_password}
                  onChange={v => setForm({ ...form, new_password: v.target.value })}
                />
              </div>
            </div>
            <div>
              <Label className="mb-1 block">确认密码</Label>
              <div className="relative">
                <Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="请再次输入新密码"
                  className="pl-9"
                  value={form.confirm_password}
                  onChange={v => setForm({ ...form, confirm_password: v.target.value })}
                />
              </div>
            </div>

            {errorMsg && <div className="text-red-500 text-sm">{errorMsg}</div>}

            <div className="flex gap-3 pt-4">
              <Button
                variant="outline"
                className="flex-1"
                type="button"
                onClick={() => navigate(-1)}
              >
                <ArrowLeft size={16} />
                返回
              </Button>
              <Button
                type="submit"
                className="flex-1"
                disabled={loading}
              >
                {loading ? '提交中...' : '确认修改'}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}

// shuaituzhibincg/web-mobile/src/views/password/index.vue
<template>
  <div class="password-page">
    <div class="form-card">
      <div class="card-header">
        <div class="header-icon">
          <el-icon :size="20" color="#4f6ef7"><Lock /></el-icon>
        </div>
        <div class="header-text">
          <h3>修改密码</h3>
          <p>请输入当前密码并设置新密码</p>
        </div>
      </div>

      <el-form :model="form" :rules="rules" ref="formRef" label-position="top">
        <el-form-item label="原密码" prop="oldPassword">
          <el-input
            v-model="form.oldPassword"
            type="password"
            placeholder="请输入原密码"
            show-password
          />
        </el-form-item>

        <el-form-item label="新密码" prop="newPassword">
          <el-input
            v-model="form.newPassword"
            type="password"
            placeholder="请输入新密码（至少6位）"
            show-password
          />
        </el-form-item>

        <el-form-item label="确认密码" prop="confirmPassword">
          <el-input
            v-model="form.confirmPassword"
            type="password"
            placeholder="请再次输入新密码"
            show-password
          />
        </el-form-item>

        <el-form-item>
          <el-button
            type="primary"
            :loading="loading"
            @click="handleSubmit"
            class="submit-btn"
          >
            提交修改
          </el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Lock } from '@element-plus/icons-vue'
import { changePassword } from '@/api/auth'

const router = useRouter()
const formRef = ref()
const loading = ref(false)

const form = reactive({
  oldPassword: '',
  newPassword: '',
  confirmPassword: ''
})

const validateConfirm = (rule, value, callback) => {
  if (value !== form.newPassword) {
    callback(new Error('两次输入的密码不一致'))
  } else {
    callback()
  }
}

const rules = {
  oldPassword: [{ required: true, message: '请输入原密码', trigger: 'blur' }],
  newPassword: [
    { required: true, message: '请输入新密码', trigger: 'blur' },
    { min: 6, message: '密码长度至少6位', trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, message: '请确认新密码', trigger: 'blur' },
    { validator: validateConfirm, trigger: 'blur' }
  ]
}

const handleSubmit = async () => {
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return

  loading.value = true
  try {
    const res = await changePassword({
      old_password: form.oldPassword,
      new_password: form.newPassword
    })
    if (res.code === 200) {
      ElMessage.success('密码修改成功')
      router.back()
    } else {
      ElMessage.error(res.message || '修改失败')
    }
  } finally {
    loading.value = false
  }
}
</script>

<style lang="scss" scoped>
.password-page {
  padding: 16px;
}

.form-card {
  background: #fff;
  border-radius: 16px;
  padding: 24px 20px;
  border: 1px solid #e2e8f0;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}

.card-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 24px;
  padding-bottom: 16px;
  border-bottom: 1px solid #f1f5f9;
}

.header-icon {
  width: 40px;
  height: 40px;
  background: #eef1fe;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.header-text {
  h3 {
    font-size: 16px;
    font-weight: 600;
    color: #1e293b;
    margin: 0 0 2px;
  }

  p {
    font-size: 13px;
    color: #94a3b8;
    margin: 0;
  }
}

.submit-btn {
  width: 100%;
  height: 46px;
  font-size: 15px;
  border-radius: 12px;
}
</style>
